site_name: FreeRTOS Kernel Book zh
site_url: https://kashima19960.github.io/FreeRTOS-Kernel-Book-zh
theme:
  name: material
markdown_extensions:
  - toc
  - tables
  - fenced_code
  - footnotes